[package]
name = "shell-download"
version = "0.11.0"
edition = "2024"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/shell-download"
readme = "README.md"
categories = ["network-programming", "command-line-utilities", "os"]
rust-version = "1.85"
description = "Zero-dependency Rust library for downloading a URL to a file using shell tools."

[lib]
path = "src/lib.rs"

[features]
default = []
url = ["dep:url"]
tempfile = ["dep:tempfile"]

[dependencies]
url = { version = "2.5", optional = true, default-features = false }
tempfile = { version = "3", optional = true }

[dev-dependencies]
dtor = "1.0.1"
